// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _489_.Net_API_example;

namespace _489_.Net_API_example.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211213101817_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_489_.Net_API_example.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iphone"
                        });
                });

            modelBuilder.Entity("_489_.Net_API_example.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CateId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CateId = 1,
                            Name = "P1",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 2,
                            CateId = 1,
                            Name = "P2",
                            Price = 4500.0
                        },
                        new
                        {
                            Id = 3,
                            CateId = 1,
                            Name = "P3",
                            Price = 3000.0
                        },
                        new
                        {
                            Id = 4,
                            CateId = 2,
                            Name = "P4",
                            Price = 4000.0
                        },
                        new
                        {
                            Id = 5,
                            CateId = 2,
                            Name = "P5",
                            Price = 4000.0
                        },
                        new
                        {
                            Id = 6,
                            CateId = 2,
                            Name = "P6",
                            Price = 4000.0
                        });
                });

            modelBuilder.Entity("_489_.Net_API_example.Models.Product", b =>
                {
                    b.HasOne("_489_.Net_API_example.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
